[package]
name = "zpack"
description = "A fast, configurable package manager which builds programs from source"
version = "0.1.0"
edition = "2024"

[features]
mpi = ["dep:mpi"]

[dependencies]
clap = { version = "4.5.39", features = ["deprecated", "derive", "cargo", "env", "unicode", "wrap_help", "string"] }
clap_complete = { version = "4.5.51", features = ["unstable-dynamic"] }
color-eyre = "0.6.5"
mpi = { version = "0.8.0", optional=true, features = ["user-operations", "derive", "complex"] }
rustpython = { version = "0.4.0", features = ["stdlib"] }
saphyr = "0.0.4"
syntect = { version = "5.2.0", features = ["default-fancy"] }

# pyo3 = { version = "0.25.0", features=["abi3", "auto-initialize", "full"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3
strip = true
debug = false
debug-assertions = false

[profile.release.package."*"]
codegen-units = 1
opt-level = 3
strip = true
debug = false
debug-assertions = false

[profile.profile]
inherits = "release"
debug = true
