[package]
name = "zpack"
description = "A fast, configurable package manager which builds programs from source"
version = "0.1.0"
edition = "2024"

[features]
mpi = ["dep:mpi"]

[dependencies]
clap = { version = "4.5.39", features = ["deprecated", "derive", "cargo", "env", "unicode", "wrap_help", "string"] }
clap_complete = { version = "4.5.51", features = ["unstable-dynamic"] }
mpi = { version = "0.8.0", optional=true, features = ["user-operations", "derive", "complex"] }
pyo3 = { version = "0.25.0", features=["abi3", "auto-initialize", "full"] }
rustpython = { version = "0.4.0", features=["stdlib"] }
saphyr = "0.0.4"
