name: Rust CI

on:
  push:
    branches: [edge, master]
    tags: ['*']
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  debug_build:
    name: Debug Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      CFLAGS_s390x_unknown_linux_gnu: '-march=z10'
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo build --features z3_bundled
      - uses: actions/upload-artifact@v4
        with:
          name: zpack-debug-${{ matrix.os }}
          path: |
            target/debug/*
            !target/debug/.*
            !target/debug/{build,deps,examples,incremental}

  debug_test:
    name: Debug Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      CFLAGS_s390x_unknown_linux_gnu: '-march=z10'
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo test --features z3_bundled

  debug_doc_test:
    name: Debug Doc Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      CFLAGS_s390x_unknown_linux_gnu: '-march=z10'
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo test --doc --features z3_bundled

  release_build:
    name: Release Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      CFLAGS_s390x_unknown_linux_gnu: '-march=z10'
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo build --release --features z3_bundled
      - uses: actions/upload-artifact@v4
        with:
          name: zpack-release-${{ matrix.os }}
          path: |
            target/release/*
            !target/release/.*
            !target/release/{build,deps,examples,incremental}

  release_test:
    name: Release Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      CFLAGS_s390x_unknown_linux_gnu: '-march=z10'
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo test --release --features z3_bundled

  release_doc_test:
    name: Release Doc Test - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      CFLAGS_s390x_unknown_linux_gnu: '-march=z10'
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo test --release --doc --features z3_bundled

  benchmarks:
    name: Benchmarks - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
    env:
      CFLAGS_s390x_unknown_linux_gnu: '-march=z10'
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo bench --features z3_bundled

  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
      Z3_SYS_BUNDLED_DIR_OVERRIDE: ${{ github.workspace }}/z3_git_source
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: Z3Prover/z3
          path: z3_git_source
          ref: z3-4.15.3
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y build-essential clang llvm-dev libclang-dev
      - run: cargo doc --no-deps --document-private-items --features z3_bundled
      - uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: target/doc/

